let appleData = [
  {
    id: 673463,
    title: "Slow Cooker Apple Pork Tenderloin",
    image: "https://spoonacular.com/recipeImages/673463-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 2,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 6008,
        amount: 2.0,
        unit: "cups",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Canned and Jarred",
        name: "beef broth",
        original: "2 cups beef broth",
        originalName: "beef broth",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/beef-broth.png",
      },
      {
        id: 10218,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Meat",
        name: "pork tenderloin",
        original: "Pork Tenderloin",
        originalName: "Pork Tenderloin",
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/pork-tenderloin-raw.png",
      },
    ],
    usedIngredients: [
      {
        id: 9003,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "apple",
        original: "apple slicer (*optional)",
        originalName: "apple slicer (*optional)",
        meta: ["(*optional)"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/apple.jpg",
      },
      {
        id: 1069003,
        amount: 2.0,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Produce",
        name: "green apples",
        original: "2 green apples",
        originalName: "green apples",
        meta: ["green"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/grannysmith-apple.png",
      },
    ],
    unusedIngredients: [],
    likes: 0,
  },
  {
    id: 660261,
    title: "Slow Cooked Applesauce",
    image: "https://spoonacular.com/recipeImages/660261-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 2010,
        amount: 0.5,
        unit: "teaspoon",
        unitLong: "teaspoons",
        unitShort: "tsp",
        aisle: "Spices and Seasonings",
        name: "cinnamon",
        original: "1/2 teaspoon cinnamon",
        originalName: "cinnamon",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/cinnamon.jpg",
      },
      {
        id: 2025,
        amount: 1.0,
        unit: "pinch",
        unitLong: "pinch",
        unitShort: "pinch",
        aisle: "Spices and Seasonings",
        name: "nutmeg",
        original: "pinch of nutmeg",
        originalName: "pinch of nutmeg",
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/ground-nutmeg.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 9003,
        amount: 5.0,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Produce",
        name: "apples",
        original: "5 apples from a local tree if possible",
        originalName: "apples from a local tree if possible",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/apple.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 2,
  },
  {
    id: 621189,
    title: "beetroot apple smoothie",
    image: "https://spoonacular.com/recipeImages/621189-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 11080,
        amount: 0.5,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Produce",
        name: "beetroot",
        original: "1/2 beetroot",
        originalName: "beetroot",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/beets.jpg",
      },
      {
        id: 9252,
        amount: 1.0,
        unit: "large",
        unitLong: "large",
        unitShort: "large",
        aisle: "Produce",
        name: "pear",
        original: "1 large pear",
        originalName: "pear",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/pears-bosc.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 1089003,
        amount: 2.0,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Produce",
        name: "granny smith apples",
        original: "2 granny smith apples",
        originalName: "granny smith apples",
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/grannysmith-apple.png",
      },
    ],
    unusedIngredients: [],
    likes: 1,
  },
  {
    id: 633547,
    title: "Baked Cinnamon Apple Slices",
    image: "https://spoonacular.com/recipeImages/633547-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 2,
    missedIngredients: [
      {
        id: 2010,
        amount: 1.5,
        unit: "tablespoons",
        unitLong: "tablespoons",
        unitShort: "Tbsp",
        aisle: "Spices and Seasonings",
        name: "cinnamon",
        original: "1 1/2 tablespoons of Cinnamon",
        originalName: "Cinnamon",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/cinnamon.jpg",
      },
      {
        id: 9299,
        amount: 0.5,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Dried Fruits;Produce;Baking",
        name: "raisins",
        original: "1/2 cup of Raisins",
        originalName: "Raisins",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/raisins.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 9003,
        amount: 4.0,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Produce",
        name: "apples",
        original:
          "4 Apples Sliced and Peeled – whatever type of apples I have in my refrigerator",
        originalName:
          "Apples Sliced and Peeled – whatever type of apples I have in my refrigerator",
        meta: ["peeled", "sliced"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/apple.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 1,
  },
  {
    id: 716433,
    title: "Easiest Breakfast Ever: Sunny Fruit Parfait",
    image: "https://spoonacular.com/recipeImages/716433-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 3,
    missedIngredients: [
      {
        id: 9299,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Dried Fruits;Produce;Baking",
        name: "raisins",
        original: "organic raisins",
        originalName: "organic raisins",
        meta: ["organic"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/raisins.jpg",
      },
      {
        id: 12036,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Savory Snacks",
        name: "sunflower seeds",
        original: "sunflower seeds",
        originalName: "sunflower seeds",
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/sunflower-seeds.jpg",
      },
      {
        id: 1116,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Milk, Eggs, Other Dairy",
        name: "yogurt",
        original: "plain yogurt, unsweetened (regular or greek)",
        originalName: "plain yogurt, unsweetened (regular or greek)",
        meta: ["plain", "unsweetened", "(regular or greek)"],
        extendedName: "unsweetened plain yogurt",
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/plain-yogurt.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 9003,
        amount: 1.0,
        unit: "serving",
        unitLong: "serving",
        unitShort: "serving",
        aisle: "Produce",
        name: "apple",
        original:
          "chopped organic apple, unpeeled (grated instead of chopped for very small children)",
        originalName:
          "chopped organic apple, unpeeled (grated instead of chopped for very small children)",
        meta: [
          "organic",
          "grated",
          "unpeeled",
          "chopped",
          "for very small children)",
        ],
        image: "https://spoonacular.com/cdn/ingredients_100x100/apple.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 93,
  },
  {
    id: 633548,
    title: "Baked Cinnamon Apple Wedges",
    image: "https://spoonacular.com/recipeImages/633548-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 3,
    missedIngredients: [
      {
        id: 19911,
        amount: 1.0,
        unit: "tsp",
        unitLong: "teaspoon",
        unitShort: "tsp",
        aisle: "Cereal",
        name: "maple syrup",
        original: "1 tsp maple syrup",
        originalName: "maple syrup",
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/maple-syrup.png",
      },
      {
        id: 2010,
        amount: 0.5,
        unit: "tsp",
        unitLong: "teaspoons",
        unitShort: "tsp",
        aisle: "Spices and Seasonings",
        name: "cinnamon",
        original: "1/2 tsp cinnamon",
        originalName: "cinnamon",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/cinnamon.jpg",
      },
      {
        id: 2025,
        amount: 0.25,
        unit: "tsp",
        unitLong: "teaspoons",
        unitShort: "tsp",
        aisle: "Spices and Seasonings",
        name: "nutmeg",
        original: "1/4 tsp nutmeg",
        originalName: "nutmeg",
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/ground-nutmeg.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 9003,
        amount: 1.0,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Produce",
        name: "apple",
        original: "1 apple",
        originalName: "apple",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/apple.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 2,
  },
  {
    id: 662665,
    title: "Swiss Bircher Muesli",
    image: "https://spoonacular.com/recipeImages/662665-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 3,
    missedIngredients: [
      {
        id: 1077,
        amount: 0.5,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Milk, Eggs, Other Dairy",
        name: "milk",
        original: "1/2 cup of Milk",
        originalName: "Milk",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/milk.png",
      },
      {
        id: 42184,
        amount: 0.5,
        unit: "cup",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Cereal",
        name: "muesli",
        original: "1/2 cup muesli",
        originalName: "muesli",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/granola.jpg",
      },
      {
        id: 43261,
        amount: 3.0,
        unit: "tablespoons",
        unitLong: "tablespoons",
        unitShort: "Tbsp",
        aisle: "Milk, Eggs, Other Dairy",
        name: "skim vanilla yoghurt",
        original: "3 tablespoons of plain or vanilla yoghurt",
        originalName: "plain or vanilla yoghurt",
        meta: ["plain"],
        extendedName: "plain skim vanilla yoghurt",
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/vanilla-yogurt.png",
      },
    ],
    usedIngredients: [
      {
        id: 9003,
        amount: 1.0,
        unit: "",
        unitLong: "",
        unitShort: "",
        aisle: "Produce",
        name: "apple",
        original: "1 Apple",
        originalName: "Apple",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/apple.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 1,
  },
  {
    id: 662175,
    title: "Sugar-Free Apple and Cinnamon Jam",
    image: "https://spoonacular.com/recipeImages/662175-312x231.jpg",
    imageType: "jpg",
    usedIngredientCount: 1,
    missedIngredientCount: 3,
    missedIngredients: [
      {
        id: 11663,
        amount: 0.5,
        unit: "teaspoon",
        unitLong: "teaspoons",
        unitShort: "tsp",
        aisle: "Ethnic Foods;Health Foods",
        name: "agar",
        original: "1/2 teaspoon agar-agar powder",
        originalName: "agar-agar powder",
        meta: [],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/white-powder.jpg",
      },
      {
        id: 1012010,
        amount: 1.0,
        unit: "teaspoon",
        unitLong: "teaspoon",
        unitShort: "tsp",
        aisle: "Spices and Seasonings",
        name: "cinnamon powder",
        original: "1 teaspoon cinnamon powder",
        originalName: "cinnamon powder",
        meta: [],
        image: "https://spoonacular.com/cdn/ingredients_100x100/cinnamon.jpg",
      },
      {
        id: 99190,
        amount: 1.5,
        unit: "cups",
        unitLong: "cups",
        unitShort: "cup",
        aisle: "Baking",
        name: "sukrin sweetener",
        original: "1 1/2 cups sweetener (I used Candarel)",
        originalName: "sweetener (I used Candarel)",
        meta: ["(I used Candarel)"],
        image:
          "https://spoonacular.com/cdn/ingredients_100x100/sugar-substitute.jpg",
      },
    ],
    usedIngredients: [
      {
        id: 9003,
        amount: 1.0,
        unit: "medium",
        unitLong: "medium",
        unitShort: "medium",
        aisle: "Produce",
        name: "apples",
        original:
          "medium Around 10 sized eating (not cooking) apples, peeled, cored and chopped into ½ inch pieces",
        originalName:
          "Around 10 sized eating (not cooking) apples, peeled, cored and chopped into ½ inch pieces",
        meta: ["cored", "peeled", "chopped", "(not cooking)"],
        image: "https://spoonacular.com/cdn/ingredients_100x100/apple.jpg",
      },
    ],
    unusedIngredients: [],
    likes: 1,
  },
];
