let appleRecipes = [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 6,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 0,
    spoonacularScore: 56.0,
    healthScore: 19.0,
    creditsText: "Jen West",
    sourceName: "Pink When",
    pricePerServing: 440.93,
    extendedIngredients: [
      {
        id: 9003,
        aisle: "Produce",
        image: "apple.jpg",
        consistency: "solid",
        name: "apple",
        nameClean: "apple",
        original: "apple slicer (*optional)",
        originalName: "apple slicer (*optional)",
        amount: 1.0,
        unit: "serving",
        meta: ["(*optional)"],
        measures: {
          us: { amount: 1.0, unitShort: "serving", unitLong: "serving" },
          metric: { amount: 1.0, unitShort: "serving", unitLong: "serving" },
        },
      },
      {
        id: 6008,
        aisle: "Canned and Jarred",
        image: "beef-broth.png",
        consistency: "liquid",
        name: "beef broth",
        nameClean: "beef broth",
        original: "2 cups beef broth",
        originalName: "beef broth",
        amount: 2.0,
        unit: "cups",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 473.176, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: 10219335,
        aisle: "Spices and Seasonings",
        image: "cinnamon-sugar.png",
        consistency: "solid",
        name: "cinnamon sugar",
        nameClean: "cinnamon sugar",
        original: "cinnamon sugar (*optional)",
        originalName: "cinnamon sugar (*optional)",
        amount: 1.0,
        unit: "serving",
        meta: ["(*optional)"],
        measures: {
          us: { amount: 1.0, unitShort: "serving", unitLong: "serving" },
          metric: { amount: 1.0, unitShort: "serving", unitLong: "serving" },
        },
      },
      {
        id: 1069003,
        aisle: "Produce",
        image: "grannysmith-apple.png",
        consistency: "solid",
        name: "green apples",
        nameClean: "green apple",
        original: "2 green apples",
        originalName: "green apples",
        amount: 2.0,
        unit: "",
        meta: ["green"],
        measures: {
          us: { amount: 2.0, unitShort: "", unitLong: "" },
          metric: { amount: 2.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 10218,
        aisle: "Meat",
        image: "pork-tenderloin-raw.png",
        consistency: "solid",
        name: "pork tenderloin",
        nameClean: "pork tenderloin",
        original: "Pork Tenderloin",
        originalName: "Pork Tenderloin",
        amount: 1.0,
        unit: "serving",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "serving", unitLong: "serving" },
          metric: { amount: 1.0, unitShort: "serving", unitLong: "serving" },
        },
      },
    ],
    id: 673463,
    title: "Slow Cooker Apple Pork Tenderloin",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl: "http://www.pinkwhen.com/slow-cooker-apple-pork-tenderloin/",
    image: "https://spoonacular.com/recipeImages/673463-556x370.jpg",
    imageType: "jpg",
    summary:
      'Slow Cooker Apple Pork Tenderloin is a <b>gluten free and primal</b> main course. For <b>$4.19 per serving</b>, this recipe <b>covers 27%</b> of your daily requirements of vitamins and minerals. One serving contains <b>486 calories</b>, <b>34g of protein</b>, and <b>12g of fat</b>. Only a few people made this recipe, and 1 would say it hit the spot. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Head to the store and pick up pork tenderloin, apples, cinnamon sugar, and a few other things to make it today. To use up the apple you could follow this main course with the <a href="https://spoonacular.com/recipes/apple-party-from-the-vault-apple-craisin-bread-pudding-515137">Apple Party! From the Vault – Apple Craisin Bread Pudding</a> as a dessert. All things considered, we decided this recipe <b>deserves a spoonacular score of 58%</b>. This score is pretty good. Try <a href="https://spoonacular.com/recipes/slow-cooker-pork-tenderloin-143861">Slow Cooker Pork Tenderloin</a>, <a href="https://spoonacular.com/recipes/havana-slow-cooker-pork-tenderloin-357547">Havana Slow Cooker Pork Tenderloin</a>, and <a href="https://spoonacular.com/recipes/slow-cooker-teriyaki-pork-tenderloin-470380">Slow Cooker Teriyaki Pork Tenderloin</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free"],
    occasions: [],
    winePairing: {
      pairedWines: ["malbec", "pinot noir", "sangiovese"],
      pairingText:
        "Pork Tenderloin can be paired with Malbec, Pinot Noir, and Sangiovese. Pinot noir's light body is great for lean cuts, medium bodied sangiovese complement meaty sauces, stews, and other multi-ingredient dishes, and full-bodied tannic malbec pairs with fatty cuts and barbecue.",
      productMatches: [
        {
          id: 502540,
          title: null,
          description:
            "The 2017 Finca La Celia Pioneer Malbec is an attractive wine with aromas of fresh and ripe fruit, in perfect harmony with the delicacy of the violets and oak aging notes. Very good attack on the palate, with fruity concentration, typical of Malbec, palate medium firm but at the same time elegant. It is an ideal Malbec to drink with the Argetine roast beef with typical “empanadas”.",
          price: "$13.99",
          imageUrl: "https://spoonacular.com/productImages/502540-312x231.jpg",
          averageRating: 0.86,
          ratingCount: 40.0,
          score: 0.8517355371900827,
          link: "https://click.linksynergy.com/deeplink?id=*QCiIS6t4gA&mid=2025&murl=https%3A%2F%2Fwww.wine.com%2Fproduct%2Fla-celia-pioneer-malbec-2017%2F613015",
        },
      ],
    },
    instructions: null,
    analyzedInstructions: [],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/slow-cooker-apple-pork-tenderloin-673463",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 0,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 2,
    spoonacularScore: 15.0,
    healthScore: 1.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 32.44,
    extendedIngredients: [
      {
        id: 9003,
        aisle: "Produce",
        image: "apple.jpg",
        consistency: "solid",
        name: "apples",
        nameClean: "apple",
        original: "5 apples from a local tree if possible",
        originalName: "apples from a local tree if possible",
        amount: 5.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 5.0, unitShort: "", unitLong: "" },
          metric: { amount: 5.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 14412,
        aisle: "Beverages",
        image: "water.png",
        consistency: "liquid",
        name: "water",
        nameClean: "water",
        original: "1 cup water (more if necessary)",
        originalName: "water (more if necessary)",
        amount: 1.0,
        unit: "cup",
        meta: ["(more if necessary)"],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 236.588, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: 19334,
        aisle: "Baking",
        image: "dark-brown-sugar.png",
        consistency: "solid",
        name: "brown sugar",
        nameClean: "golden brown sugar",
        original: "3 tablespoons brown sugar",
        originalName: "brown sugar",
        amount: 3.0,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: { amount: 3.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: { amount: 3.0, unitShort: "Tbsps", unitLong: "Tbsps" },
        },
      },
      {
        id: 2010,
        aisle: "Spices and Seasonings",
        image: "cinnamon.jpg",
        consistency: "solid",
        name: "cinnamon",
        nameClean: "cinnamon",
        original: "1/2 teaspoon cinnamon",
        originalName: "cinnamon",
        amount: 0.5,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
          metric: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
        },
      },
      {
        id: 2025,
        aisle: "Spices and Seasonings",
        image: "ground-nutmeg.jpg",
        consistency: "solid",
        name: "nutmeg",
        nameClean: "nutmeg",
        original: "pinch of nutmeg",
        originalName: "pinch of nutmeg",
        amount: 1.0,
        unit: "pinch",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "pinch", unitLong: "pinch" },
          metric: { amount: 1.0, unitShort: "pinch", unitLong: "pinch" },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "solid",
        name: "salt",
        nameClean: "table salt",
        original: "pinch of salt",
        originalName: "pinch of salt",
        amount: 1.0,
        unit: "pinch",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "pinch", unitLong: "pinch" },
          metric: { amount: 1.0, unitShort: "pinch", unitLong: "pinch" },
        },
      },
    ],
    id: 660261,
    title: "Slow Cooked Applesauce",
    readyInMinutes: 45,
    servings: 10,
    sourceUrl:
      "https://www.foodista.com/recipe/XB3V6NRQ/slow-cooked-applesauce",
    image: "https://spoonacular.com/recipeImages/660261-556x370.jpg",
    imageType: "jpg",
    summary:
      'Slow Cooked Applesauce takes about <b>approximately 45 minutes</b> from beginning to end. One serving contains <b>62 calories</b>, <b>0g of protein</b>, and <b>0g of fat</b>. This recipe serves 10. For <b>32 cents per serving</b>, this recipe <b>covers 1%</b> of your daily requirements of vitamins and minerals. 1 person has made this recipe and would make it again. It is a good option if you\'re following a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> diet. Only a few people really liked this side dish. If you have apples from a local tree if possible, nutmeg, brown sugar, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. Taking all factors into account, this recipe <b>earns a spoonacular score of 10%</b>, which is rather bad. <a href="https://spoonacular.com/recipes/slow-cooker-applesauce-482526">Slow Cooker Applesauce</a>, <a href="https://spoonacular.com/recipes/slow-cooker-applesauce-555428">Slow Cooker Applesauce</a>, and <a href="https://spoonacular.com/recipes/slow-cooker-cranberry-applesauce-623982">Slow cooker cranberry applesauce</a> are very similar to this recipe.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    occasions: [],
    winePairing: {},
    instructions:
      "Peel and core apples. Thinly slice and rough chop them. Add them to a medium-to large pot over medium-high heat on the stove. Add water and stir. Once the water starts to simmer, reduce heat to med-low and stir. Add cinnamon, nutmeg and salt and stir. Cook over medium low heat for 2 hours, stirring occasionally. Depending on how you like the consistency of your applesauce, cook another hour for softer sauce.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Peel and core apples. Thinly slice and rough chop them.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 2,
            step: "Add them to a medium-to large pot over medium-high heat on the stove.",
            ingredients: [],
            equipment: [
              {
                id: 404794,
                name: "stove",
                localizedName: "stove",
                image: "oven.jpg",
              },
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
          {
            number: 3,
            step: "Add water and stir. Once the water starts to simmer, reduce heat to med-low and stir.",
            ingredients: [
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step: "Add cinnamon, nutmeg and salt and stir. Cook over medium low heat for 2 hours, stirring occasionally. Depending on how you like the consistency of your applesauce, cook another hour for softer sauce.",
            ingredients: [
              {
                id: 9019,
                name: "applesauce",
                localizedName: "applesauce",
                image: "applesauce.png",
              },
              {
                id: 2010,
                name: "cinnamon",
                localizedName: "cinnamon",
                image: "cinnamon.jpg",
              },
              {
                id: 2025,
                name: "nutmeg",
                localizedName: "nutmeg",
                image: "ground-nutmeg.jpg",
              },
              { id: 0, name: "sauce", localizedName: "sauce", image: "" },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [],
            length: { number: 120, unit: "minutes" },
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/slow-cooked-applesauce-660261",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 0,
    gaps: "GAPS_6",
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 38.0,
    healthScore: 5.0,
    creditsText: "swasthi",
    license: "spoonacular's terms",
    sourceName: "spoonacular",
    pricePerServing: 129.95,
    extendedIngredients: [
      {
        id: 11080,
        aisle: "Produce",
        image: "beets.jpg",
        consistency: "solid",
        name: "beetroot",
        nameClean: "red beet",
        original: "1/2 beetroot",
        originalName: "beetroot",
        amount: 0.5,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 0.5, unitShort: "", unitLong: "" },
          metric: { amount: 0.5, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 1089003,
        aisle: "Produce",
        image: "grannysmith-apple.png",
        consistency: "solid",
        name: "granny smith apples",
        nameClean: "granny smith apple",
        original: "2 granny smith apples",
        originalName: "granny smith apples",
        amount: 2.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "", unitLong: "" },
          metric: { amount: 2.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 9252,
        aisle: "Produce",
        image: "pears-bosc.jpg",
        consistency: "solid",
        name: "pear",
        nameClean: "pear",
        original: "1 large pear",
        originalName: "pear",
        amount: 1.0,
        unit: "large",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "large", unitLong: "large" },
          metric: { amount: 1.0, unitShort: "large", unitLong: "large" },
        },
      },
    ],
    id: 621189,
    title: "beetroot apple smoothie",
    author: "swasthi",
    readyInMinutes: 5,
    servings: 2,
    sourceUrl: "https://spoonacular.com/-1417430524222",
    image: "https://spoonacular.com/recipeImages/621189-556x370.jpg",
    imageType: "jpg",
    summary:
      'Beetroot apple smoothie might be just the morn meal you are searching for. This recipe serves 2 and costs $1.21 per serving. One serving contains <b>154 calories</b>, <b>1g of protein</b>, and <b>0g of fat</b>. A mixture of beetroot, granny smith apples, pear, and a handful of other ingredients are all it takes to make this recipe so flavorful. It is a good option if you\'re following a <b>caveman, gluten free, primal, and whole 30</b> diet. From preparation to the plate, this recipe takes about <b>5 minutes</b>. Try <a href="https://spoonacular.com/recipes/-beetroot-banana-berry-smoothie-ft-love-beets-baby-beetroot-494132">[] Beetroot, Banana & Berry Smoothie ft. Love Beets Baby Beetroot</a>, <a href="https://spoonacular.com/recipes/chocolate-beetroot-smoothie-+-a-cookbook-update-512516">Chocolate Beetroot Smoothie + A Cookbook Update</a>, and <a href="https://spoonacular.com/recipes/apple-beetroot-and-spinach-9336">Apple, Beetroot And Spinach</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "vegan",
    ],
    occasions: [],
    winePairing: {},
    instructions:
      '<p>for instructions check<a href="http://indianhealthyrecipes.com/beetroot-apple-smoothie-the-best-beetroot-smoothie/">&nbsp;indianhealthyrecipes.com</a><a href="indianhealthyrecipes.com"></a></p>',
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "for instructions check&nbsp;indianhealthyrecipes.com",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/beetroot-apple-smoothie-621189",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 0,
    gaps: "GAPS_6",
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 37.0,
    healthScore: 4.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 56.52,
    extendedIngredients: [
      {
        id: 9003,
        aisle: "Produce",
        image: "apple.jpg",
        consistency: "solid",
        name: "apples",
        nameClean: "apple",
        original:
          "4 Apples Sliced and Peeled – whatever type of apples I have in my refrigerator",
        originalName:
          "Apples Sliced and Peeled – whatever type of apples I have in my refrigerator",
        amount: 4.0,
        unit: "",
        meta: ["peeled", "sliced"],
        measures: {
          us: { amount: 4.0, unitShort: "", unitLong: "" },
          metric: { amount: 4.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 2010,
        aisle: "Spices and Seasonings",
        image: "cinnamon.jpg",
        consistency: "solid",
        name: "cinnamon",
        nameClean: "cinnamon",
        original: "1 1/2 tablespoons of Cinnamon",
        originalName: "Cinnamon",
        amount: 1.5,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: { amount: 1.5, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: { amount: 1.5, unitShort: "Tbsps", unitLong: "Tbsps" },
        },
      },
      {
        id: 9299,
        aisle: "Dried Fruits;Produce;Baking",
        image: "raisins.jpg",
        consistency: "solid",
        name: "raisins",
        nameClean: "raisins",
        original: "1/2 cup of Raisins",
        originalName: "Raisins",
        amount: 0.5,
        unit: "cup",
        meta: [],
        measures: {
          us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 118.294, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: null,
        aisle: "?",
        image: null,
        consistency: null,
        name: "earth balance",
        nameClean: null,
        original: "2 tablespoons of Earth Balance – melted",
        originalName: "Earth Balance – melted",
        amount: 2.0,
        unit: "tablespoons",
        meta: ["melted"],
        measures: {
          us: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
        },
      },
    ],
    id: 633547,
    title: "Baked Cinnamon Apple Slices",
    readyInMinutes: 45,
    servings: 6,
    sourceUrl:
      "http://www.foodista.com/recipe/JQWGC7VW/baked-cinnamon-apple-slices",
    image: "https://spoonacular.com/recipeImages/633547-556x370.jpg",
    imageType: "jpg",
    summary:
      'Baked Cinnamon Apple Slices might be just the side dish you are searching for. One serving contains <b>104 calories</b>, <b>1g of protein</b>, and <b>0g of fat</b>. This caveman, gluten free, primal, and whole 30 recipe serves 6 and costs <b>57 cents per serving</b>. This recipe from Foodista has 1 fans. Head to the store and pick up apples and - whatever type of apples i have in my refrigerator, raisins, earth balance, and a few other things to make it today. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 40%</b>. This score is not so super. Try <a href="https://spoonacular.com/recipes/moms-baked-apple-slices-245248">Mom’s Baked Apple Slices</a>, <a href="https://spoonacular.com/recipes/baked-apple-slices-437570">Baked Apple Slices</a>, and <a href="https://spoonacular.com/recipes/baked-pork-chops-with-apple-slices-421215">Baked Pork Chops with Apple Slices</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "vegan",
    ],
    occasions: [],
    winePairing: {},
    instructions:
      "<ol><li>Mix ingredients together except the raisins.  Place in baking dish and in oven at 350 Degrees for 30 minutes.</li><li>Add raisins the last 5 minutes of baking.</li><li>Serve and enjoy!</li><li>Use Organic Ingredients if Available</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Mix ingredients together except the raisins.",
            ingredients: [
              {
                id: 9299,
                name: "raisins",
                localizedName: "raisins",
                image: "raisins.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 2,
            step: "Place in baking dish and in oven at 350 Degrees for 30 minutes.",
            ingredients: [],
            equipment: [
              {
                id: 404646,
                name: "baking pan",
                localizedName: "baking pan",
                image: "roasting-pan.jpg",
              },
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: { number: 30, unit: "minutes" },
          },
          {
            number: 3,
            step: "Add raisins the last 5 minutes of baking.",
            ingredients: [
              {
                id: 9299,
                name: "raisins",
                localizedName: "raisins",
                image: "raisins.jpg",
              },
            ],
            equipment: [],
            length: { number: 5, unit: "minutes" },
          },
          {
            number: 4,
            step: "Serve and enjoy!Use Organic Ingredients if Available",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/baked-cinnamon-apple-slices-633547",
  },
];
