let recipeData = [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 12,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 90.0,
    healthScore: 86.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 538.24,
    extendedIngredients: [
      {
        id: 23657,
        aisle: "Meat",
        image: "flank-steak.jpg",
        consistency: "solid",
        name: "flank steak",
        nameClean: "flank steak",
        original: "1 pound flank steak, 1-inch thick",
        originalName: "flank steak, 1-inch thick",
        amount: 1.0,
        unit: "pound",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "lb", unitLong: "pound" },
          metric: { amount: 453.592, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "liquid",
        name: "olive oil",
        nameClean: "olive oil",
        original: "2 tablespoons olive oil",
        originalName: "olive oil",
        amount: 2.0,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "solid",
        name: "Salt & Pepper",
        nameClean: "salt and pepper",
        original: "salt and pepper to season",
        originalName: "salt and pepper to season",
        amount: 4.0,
        unit: "servings",
        meta: [],
        measures: {
          us: { amount: 4.0, unitShort: "servings", unitLong: "servings" },
          metric: { amount: 4.0, unitShort: "servings", unitLong: "servings" },
        },
      },
      {
        id: 10011282,
        aisle: "Produce",
        image: "red-onion.png",
        consistency: "solid",
        name: "red onion",
        nameClean: "red onion",
        original: '1 red onion, sliced into 1" rings',
        originalName: 'red onion, sliced into 1" rings',
        amount: 1.0,
        unit: "",
        meta: ["red", 'sliced into 1" rings'],
        measures: {
          us: { amount: 1.0, unitShort: "", unitLong: "" },
          metric: { amount: 1.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 11266,
        aisle: "Produce",
        image: "mushrooms.png",
        consistency: "solid",
        name: "baby bella mushrooms",
        nameClean: "crimini mushrooms",
        original: "4 ounces baby bella mushrooms, quartered",
        originalName: "baby bella mushrooms, quartered",
        amount: 4.0,
        unit: "ounces",
        meta: ["quartered"],
        measures: {
          us: { amount: 4.0, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 113.398, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 10021052,
        aisle: "Produce",
        image: "mixed-greens-or-mesclun.jpg",
        consistency: "solid",
        name: "spring mix",
        nameClean: "spring mix",
        original: "5 ounces spring mix",
        originalName: "spring mix",
        amount: 5.0,
        unit: "ounces",
        meta: [],
        measures: {
          us: { amount: 5.0, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 141.748, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 10311529,
        aisle: "Produce",
        image: "cherry-tomatoes.png",
        consistency: "solid",
        name: "cherry tomatoes",
        nameClean: "cherry tomato",
        original: "1 pint cherry tomatoes, halved",
        originalName: "cherry tomatoes, halved",
        amount: 1.0,
        unit: "pint",
        meta: ["halved"],
        measures: {
          us: { amount: 1.0, unitShort: "pts", unitLong: "pint" },
          metric: { amount: 1.0, unitShort: "pts", unitLong: "pint" },
        },
      },
      {
        id: 9037,
        aisle: "Produce",
        image: "avocado.jpg",
        consistency: "solid",
        name: "avocado",
        nameClean: "avocado",
        original: "1 avocado, sliced",
        originalName: "avocado, sliced",
        amount: 1.0,
        unit: "",
        meta: ["sliced"],
        measures: {
          us: { amount: 1.0, unitShort: "", unitLong: "" },
          metric: { amount: 1.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 11297,
        aisle: "Produce;Spices and Seasonings",
        image: "parsley.jpg",
        consistency: "solid",
        name: "parsley",
        nameClean: "parsley",
        original: "1 cup lightly packed fresh parsley",
        originalName: "lightly packed fresh parsley",
        amount: 1.0,
        unit: "cup",
        meta: ["fresh", "packed"],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 236.588, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "solid",
        name: "garlic",
        nameClean: "garlic",
        original: "2 large cloves garlic",
        originalName: "garlic",
        amount: 2.0,
        unit: "large cloves",
        meta: [],
        measures: {
          us: {
            amount: 2.0,
            unitShort: "large cloves",
            unitLong: "large cloves",
          },
          metric: {
            amount: 2.0,
            unitShort: "large cloves",
            unitLong: "large cloves",
          },
        },
      },
      {
        id: 2042,
        aisle: "Spices and Seasonings",
        image: "thyme.jpg",
        consistency: "solid",
        name: "dried thyme",
        nameClean: "dried thyme",
        original: "1 teaspoon dried thyme",
        originalName: "dried thyme",
        amount: 1.0,
        unit: "teaspoon",
        meta: ["dried"],
        measures: {
          us: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
          metric: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
        },
      },
      {
        id: 1032009,
        aisle: "Spices and Seasonings",
        image: "red-pepper-flakes.jpg",
        consistency: "solid",
        name: "red pepper flakes",
        nameClean: "red pepper flakes",
        original: "1/4 teaspoon red pepper flakes",
        originalName: "red pepper flakes",
        amount: 0.25,
        unit: "teaspoon",
        meta: ["red"],
        measures: {
          us: { amount: 0.25, unitShort: "tsps", unitLong: "teaspoons" },
          metric: { amount: 0.25, unitShort: "tsps", unitLong: "teaspoons" },
        },
      },
      {
        id: 98904,
        aisle: "Canned and Jarred;Health Foods",
        image: "chicken-broth.png",
        consistency: "liquid",
        name: "bone broth",
        nameClean: "bone broth",
        original: "1/4 cup bone broth",
        originalName: "bone broth",
        amount: 0.25,
        unit: "cup",
        meta: [],
        measures: {
          us: { amount: 0.25, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 59.147, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: 1022068,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "red-wine-vinegar.jpg",
        consistency: "liquid",
        name: "red wine vinegar",
        nameClean: "red wine vinegar",
        original: "1/4 cup organic red wine vinegar",
        originalName: "organic red wine vinegar",
        amount: 0.25,
        unit: "cup",
        meta: ["red", "organic"],
        measures: {
          us: { amount: 0.25, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 59.147, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: 1034053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "liquid",
        name: "extra virgin olive oil",
        nameClean: "extra virgin olive oil",
        original: "1/4 cup extra virgin olive oil",
        originalName: "extra virgin olive oil",
        amount: 0.25,
        unit: "cup",
        meta: [],
        measures: {
          us: { amount: 0.25, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 59.147, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "solid",
        name: "salt",
        nameClean: "table salt",
        original: "1/2 teaspoon salt",
        originalName: "salt",
        amount: 0.5,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
          metric: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
        },
      },
      {
        id: 1002030,
        aisle: "Spices and Seasonings",
        image: "pepper.jpg",
        consistency: "solid",
        name: "black pepper",
        nameClean: "black pepper",
        original: "1/8 teaspoon freshly ground black pepper",
        originalName: "freshly ground black pepper",
        amount: 0.125,
        unit: "teaspoon",
        meta: ["black", "freshly ground"],
        measures: {
          us: { amount: 0.125, unitShort: "tsps", unitLong: "teaspoons" },
          metric: { amount: 0.125, unitShort: "tsps", unitLong: "teaspoons" },
        },
      },
    ],
    id: 1096025,
    title: "Steak Salad with Chimichurri Sauce",
    readyInMinutes: 30,
    servings: 4,
    sourceUrl:
      "https://www.foodista.com/recipe/ZSDGBCXH/steak-salad-with-chimichurri-sauce",
    image: "https://spoonacular.com/recipeImages/1096025-556x370.jpg",
    imageType: "jpg",
    summary:
      'If you want to add more <b>gluten free and dairy free</b> recipes to your recipe box, Steak Salad with Chimichurri Sauce might be a recipe you should try. This recipe serves 4. This main course has <b>475 calories</b>, <b>29g of protein</b>, and <b>34g of fat</b> per serving. For <b>$5.38 per serving</b>, this recipe <b>covers 32%</b> of your daily requirements of vitamins and minerals. If you have red wine vinegar, bone broth, salt, and a few other ingredients on hand, you can make it. 1 person found this recipe to be delicious and satisfying. This recipe is typical of Latin American cuisine. It is perfect for <b>valentin day</b>. From preparation to the plate, this recipe takes roughly <b>30 minutes</b>. It is brought to you by Foodista. Overall, this recipe earns a <b>great spoonacular score of 87%</b>. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/steak-with-chimichurri-sauce-carne-con-chimichurri-1294491">Steak with Chimichurri Sauce (Carne con Chimichurri)</a>, <a href="https://spoonacular.com/recipes/bistec-argentino-al-chimichurri-steak-with-chimichurri-sauce-1194721">Bistec Argentino al Chimichurri (Steak with Chimichurri Sauce)</a>, and <a href="https://spoonacular.com/recipes/bistec-argentino-al-chimichurri-steak-with-chimichurri-sauce-144447">Bistec Argentino al Chimichurri (Steak with Chimichurri Sauce)</a>.',
    cuisines: ["South American", "Latin American"],
    dishTypes: [
      "side dish",
      "lunch",
      "salad",
      "main course",
      "main dish",
      "dinner",
    ],
    diets: ["gluten free", "dairy free", "paleolithic", "primal"],
    occasions: ["valentine's day", "father's day"],
    winePairing: {
      pairedWines: ["chardonnay", "gruener veltliner", "sauvignon blanc"],
      pairingText:
        "Salad can be paired with Chardonnay, Gruener Veltliner, and Sauvignon Blanc. Sauvignon Blanc and Gruner Veltliner both have herby notes that complement salads with enough acid to match tart vinaigrettes, while a Chardonnay can be a good pick for creamy salad dressings.",
      productMatches: [
        {
          id: 478030,
          title: null,
          description:
            "The 2017 Chardonnay is vibrant and rich with enticing aromas that lead to a firm core of pear, apple and apricot flavors shaded by lightly-spiced oak. On the palate, the wine offers layer upon layer of lingering flavors. The wine highlights varietal purity with elegance and freshness on the palate.The Chardonnay was picked from 4 to 31-year-old vinesfrom select portions of nine vineyard blocks, which areplanted at an elevation of 1,413-1,494 feet. This year’s selection comprised of 10 Chardonnay clones—nine Burgundian and the acclaimed Heritage Weimer Selection—that together create the complexity in aromatics andflavors we seek for our Mountain Select Chardonnay.",
          price: "$28.99",
          imageUrl: "https://spoonacular.com/productImages/478030-312x231.jpg",
          averageRating: 0.9,
          ratingCount: 24.0,
          score: 0.8863013698630138,
          link: "https://click.linksynergy.com/deeplink?id=*QCiIS6t4gA&mid=2025&murl=https%3A%2F%2Fwww.wine.com%2Fproduct%2Fantica-chardonnay-mountain-select-2017%2F523019",
        },
      ],
    },
    instructions:
      "<ol><li>Preheat grill to medium high heat.</li><li>Season red onion rings and mushrooms with 1 tablespoon olive oil, salt and pepper to taste. Place onion rings and mushrooms on grill. Grill for 4-5 minutes per side until char marks appear. Remove and set aside.</li><li>Take steak out of your fridge and let it sit in the room temperature for 5 minutes. Use a paper towel to gently pat the surface of both sides of the steak dry.</li><li>Brush olive oil on both sides of the steak or use olive oil cooking spray. Generously season the steak with salt and freshly ground pepper.</li><li>Place the steak on the grill. Grill each side for 3-5 minutes until the internal temperature of the steak reaches 145°F for medium doneness; 135°F for medium rare and 155°F for medium well. Let rest for 5 minutes before slicing.</li><li>To make the Chimichurri sauce, place all ingredients in a food processor, blend for about 30 seconds or until all ingredients are combined well (any remaining sauce can be stored in the refrigerator for up to 2 weeks).</li><li>To assemble, arrange baby spinach spring mix on the bottom of a large serving plate, followed by the onion rings and mushrooms. Slice the steak and place on top of the vegetables. Top with cherry tomatoes and sliced avocado.</li><li><span></span>Drizzle the Chimichurri sauce over the steak salad and serve!</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat grill to medium high heat.Season red onion rings and mushrooms with 1 tablespoon olive oil, salt and pepper to taste.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
              {
                id: 11260,
                name: "mushrooms",
                localizedName: "mushrooms",
                image: "mushrooms.png",
              },
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 10011282,
                name: "red onion",
                localizedName: "red onion",
                image: "red-onion.png",
              },
            ],
            equipment: [
              {
                id: 404706,
                name: "grill",
                localizedName: "grill",
                image: "grill.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Place onion rings and mushrooms on grill. Grill for 4-5 minutes per side until char marks appear.",
            ingredients: [
              {
                id: 11260,
                name: "mushrooms",
                localizedName: "mushrooms",
                image: "mushrooms.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [
              {
                id: 404706,
                name: "grill",
                localizedName: "grill",
                image: "grill.jpg",
              },
            ],
            length: { number: 5, unit: "minutes" },
          },
          {
            number: 3,
            step: "Remove and set aside.Take steak out of your fridge and let it sit in the room temperature for 5 minutes. Use a paper towel to gently pat the surface of both sides of the steak dry.",
            ingredients: [
              {
                id: 23232,
                name: "steak",
                localizedName: "steak",
                image: "ribeye-raw.jpg",
              },
            ],
            equipment: [
              {
                id: 405895,
                name: "paper towels",
                localizedName: "paper towels",
                image: "paper-towels.jpg",
              },
            ],
            length: { number: 5, unit: "minutes" },
          },
          {
            number: 4,
            step: "Brush olive oil on both sides of the steak or use olive oil cooking spray. Generously season the steak with salt and freshly ground pepper.",
            ingredients: [
              {
                id: 1004679,
                name: "olive oil spray",
                localizedName: "olive oil spray",
                image: "cooking-spray.png",
              },
              {
                id: 1002030,
                name: "ground black pepper",
                localizedName: "ground black pepper",
                image: "pepper.jpg",
              },
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 23232,
                name: "steak",
                localizedName: "steak",
                image: "ribeye-raw.jpg",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: "Place the steak on the grill. Grill each side for 3-5 minutes until the internal temperature of the steak reaches 145°F for medium doneness; 135°F for medium rare and 155°F for medium well.",
            ingredients: [
              {
                id: 23232,
                name: "steak",
                localizedName: "steak",
                image: "ribeye-raw.jpg",
              },
            ],
            equipment: [
              {
                id: 404706,
                name: "grill",
                localizedName: "grill",
                image: "grill.jpg",
              },
            ],
            length: { number: 5, unit: "minutes" },
          },
          {
            number: 6,
            step: "Let rest for 5 minutes before slicing.To make the Chimichurri sauce, place all ingredients in a food processor, blend for about 30 seconds or until all ingredients are combined well (any remaining sauce can be stored in the refrigerator for up to 2 weeks).To assemble, arrange baby spinach spring mix on the bottom of a large serving plate, followed by the onion rings and mushrooms. Slice the steak and place on top of the vegetables. Top with cherry tomatoes and sliced avocado.",
            ingredients: [
              {
                id: 0,
                name: "chimichurri",
                localizedName: "chimichurri",
                image: "",
              },
              {
                id: 10311529,
                name: "cherry tomato",
                localizedName: "cherry tomato",
                image: "cherry-tomatoes.png",
              },
              {
                id: 11457,
                name: "baby spinach",
                localizedName: "baby spinach",
                image: "spinach.jpg",
              },
              {
                id: 10021052,
                name: "spring mix",
                localizedName: "spring mix",
                image: "mixed-greens-or-mesclun.jpg",
              },
              {
                id: 11583,
                name: "vegetable",
                localizedName: "vegetable",
                image: "mixed-vegetables.png",
              },
              {
                id: 11260,
                name: "mushrooms",
                localizedName: "mushrooms",
                image: "mushrooms.png",
              },
              {
                id: 9037,
                name: "avocado",
                localizedName: "avocado",
                image: "avocado.jpg",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
              { id: 0, name: "sauce", localizedName: "sauce", image: "" },
              {
                id: 23232,
                name: "steak",
                localizedName: "steak",
                image: "ribeye-raw.jpg",
              },
            ],
            equipment: [
              {
                id: 404771,
                name: "food processor",
                localizedName: "food processor",
                image: "food-processor.png",
              },
            ],
            length: { number: 5, unit: "minutes" },
          },
          {
            number: 7,
            step: "Drizzle the Chimichurri sauce over the steak salad and serve!",
            ingredients: [
              {
                id: 0,
                name: "chimichurri",
                localizedName: "chimichurri",
                image: "",
              },
              {
                id: 23232,
                name: "steak",
                localizedName: "steak",
                image: "ribeye-raw.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/steak-salad-with-chimichurri-sauce-1096025",
  },
  {
    vegetarian: true,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 22,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 6,
    spoonacularScore: 96.0,
    healthScore: 75.0,
    creditsText: "coffeebean",
    license: "spoonacular's terms",
    sourceName: "spoonacular",
    pricePerServing: 458.91,
    extendedIngredients: [
      {
        id: 12061,
        aisle: "Nuts",
        image: "almonds.jpg",
        consistency: "solid",
        name: "almonds",
        nameClean: "almonds",
        original: "15 grams almonds",
        originalName: "almonds",
        amount: 15.0,
        unit: "grams",
        meta: [],
        measures: {
          us: { amount: 0.529, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 15.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 9037,
        aisle: "Produce",
        image: "avocado.jpg",
        consistency: "solid",
        name: "avocado",
        nameClean: "avocado",
        original: "1/2 avocado",
        originalName: "avocado",
        amount: 0.5,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 0.5, unitShort: "", unitLong: "" },
          metric: { amount: 0.5, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 2069,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "balsamic-vinegar.jpg",
        consistency: "liquid",
        name: "balsamic vinegar",
        nameClean: "balsamic vinegar",
        original: "5 ml balsamic vinegar",
        originalName: "balsamic vinegar",
        amount: 5.0,
        unit: "ml",
        meta: [],
        measures: {
          us: { amount: 0.169, unitShort: "fl. oz", unitLong: "fl. ozs" },
          metric: { amount: 5.0, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: 1009,
        aisle: "Cheese",
        image: "cheddar-cheese.png",
        consistency: "solid",
        name: "cheddar cheese",
        nameClean: "cheddar cheese",
        original: "1/4 cup (30 grams) cheddar cheese",
        originalName: "1/4 cup cheddar cheese",
        amount: 30.0,
        unit: "grams",
        meta: [],
        measures: {
          us: { amount: 1.058, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 30.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 16033,
        aisle: "Pasta and Rice;Canned and Jarred",
        image: "kidney-beans.jpg",
        consistency: "solid",
        name: "kidney beans",
        nameClean: "kidney beans",
        original: "1/2 cup (113 grams) cooked kidney beans",
        originalName: "1/2 cup cooked kidney beans",
        amount: 113.0,
        unit: "grams",
        meta: ["cooked"],
        measures: {
          us: { amount: 3.986, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 113.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 21052,
        aisle: "Produce",
        image: "mixed-greens-or-mesclun.jpg",
        consistency: "solid",
        name: "mixed greens",
        nameClean: "mesclun",
        original: "150 grams mixed greens",
        originalName: "mixed greens",
        amount: 150.0,
        unit: "grams",
        meta: ["mixed"],
        measures: {
          us: { amount: 5.291, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 150.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "liquid",
        name: "olive oil",
        nameClean: "olive oil",
        original: "10 ml olive oil",
        originalName: "olive oil",
        amount: 10.0,
        unit: "ml",
        meta: [],
        measures: {
          us: { amount: 0.338, unitShort: "fl. oz", unitLong: "fl. ozs" },
          metric: { amount: 10.0, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: 12585,
        aisle: "Nuts;Savory Snacks",
        image: "cashews.jpg",
        consistency: "solid",
        name: "salted roasted cashews",
        nameClean: "salted roasted cashews",
        original: "15 grams roasted salted cashews",
        originalName: "roasted salted cashews",
        amount: 15.0,
        unit: "grams",
        meta: ["salted"],
        measures: {
          us: { amount: 0.529, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 15.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 11955,
        aisle: "Canned and Jarred;Produce",
        image: "sundried-tomatoes.jpg",
        consistency: "solid",
        name: "sundried tomatoes",
        nameClean: "sun dried tomatoes",
        original: "2-3 sundried tomatoes",
        originalName: "sundried tomatoes",
        amount: 2.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "", unitLong: "" },
          metric: { amount: 2.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 6168,
        aisle: "Condiments",
        image: "hot-sauce-or-tabasco.png",
        consistency: "liquid",
        name: "tabasco",
        nameClean: "hot sauce",
        original: "2 dashes (or more if you like it hot!) Tabasco",
        originalName: "(or more if you like it hot!) Tabasco",
        amount: 2.0,
        unit: "dashes",
        meta: ["( if you like it hot!)"],
        measures: {
          us: { amount: 2.0, unitShort: "dashes", unitLong: "dashes" },
          metric: { amount: 2.0, unitShort: "dashes", unitLong: "dashes" },
        },
      },
    ],
    id: 157344,
    title: "Spicy Salad with Kidney Beans, Cheddar, and Nuts",
    author: "coffeebean",
    readyInMinutes: 10,
    servings: 1,
    sourceUrl: "http://spoonacular.com/-1384191937003",
    image: "https://spoonacular.com/recipeImages/157344-556x370.jpg",
    imageType: "jpg",
    summary:
      'Spicy Salad with Kidney Beans, Cheddar, and Nuts might be just the main course you are searching for. For <b>$4.59 per serving</b>, this recipe <b>covers 37%</b> of your daily requirements of vitamins and minerals. This recipe makes 1 servings with <b>725 calories</b>, <b>27g of protein</b>, and <b>50g of fat</b> each. A mixture of almonds, avocado, kidney beans, and a handful of other ingredients are all it takes to make this recipe so tasty. To use up the avocado you could follow this main course with the <a href="https://spoonacular.com/recipes/chocolate-avocado-mousse-quick-dark-chocolate-avocado-mousse-486646">chocolate avocado mousse | quick dark chocolate avocado mousse</a> as a dessert. From preparation to the plate, this recipe takes about <b>10 minutes</b>. It is a good option if you\'re following a <b>gluten free and vegetarian</b> diet. Try <a href="https://spoonacular.com/recipes/turkey-sausages-with-spicy-kidney-beans-75450">Turkey Sausages With Spicy Kidney Beans</a>, <a href="https://spoonacular.com/recipes/spicy-chopped-kidney-bean-salad-506484">Spicy Chopped Kidney Bean Salad</a>, and <a href="https://spoonacular.com/recipes/stoneground-grits-with-cheddar-cheese-and-spicy-black-beans-meatless-monday-524536">Stoneground Grits with Cheddar Cheese and Spicy Black Beans – Meatless Monday</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["salad"],
    diets: ["gluten free", "lacto ovo vegetarian"],
    occasions: [],
    winePairing: {},
    instructions:
      "<p>     1. Rinse and drain the kidney beans, cut the sundried tomatoes, and tear the slice of cheese into small pieces.</p><p>     2. Put the mixed greens in a bowl and top with kidney beans, sundried tomatoes, cheddar cheese, and nuts.</p><p>     3. Mix together the olive oil, balsamic vinegar, and hot sauce in a small bowl. Pour the dressing over the salad.</p><p>     Fast, easy, and healthy-- one of my favorite lunches!</p>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Rinse and drain the kidney beans, cut the sundried tomatoes, and tear the slice of cheese into small pieces.",
            ingredients: [
              {
                id: 11955,
                name: "sun dried tomatoes",
                localizedName: "sun dried tomatoes",
                image: "sundried-tomatoes.jpg",
              },
              {
                id: 16033,
                name: "kidney beans",
                localizedName: "kidney beans",
                image: "kidney-beans.jpg",
              },
              {
                id: 1041009,
                name: "cheese",
                localizedName: "cheese",
                image: "cheddar-cheese.png",
              },
            ],
            equipment: [],
          },
          {
            number: 2,
            step: "Put the mixed greens in a bowl and top with kidney beans, sundried tomatoes, cheddar cheese, and nuts.",
            ingredients: [
              {
                id: 11955,
                name: "sun dried tomatoes",
                localizedName: "sun dried tomatoes",
                image: "sundried-tomatoes.jpg",
              },
              {
                id: 1009,
                name: "cheddar cheese",
                localizedName: "cheddar cheese",
                image: "cheddar-cheese.png",
              },
              {
                id: 16033,
                name: "kidney beans",
                localizedName: "kidney beans",
                image: "kidney-beans.jpg",
              },
              {
                id: 21052,
                name: "mixed greens",
                localizedName: "mixed greens",
                image: "mixed-greens-or-mesclun.jpg",
              },
              {
                id: 12135,
                name: "nuts",
                localizedName: "nuts",
                image: "nuts-mixed.jpg",
              },
            ],
            equipment: [
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
          },
          {
            number: 3,
            step: "Mix together the olive oil, balsamic vinegar, and hot sauce in a small bowl.",
            ingredients: [
              {
                id: 2069,
                name: "balsamic vinegar",
                localizedName: "balsamic vinegar",
                image: "balsamic-vinegar.jpg",
              },
              {
                id: 6168,
                name: "hot sauce",
                localizedName: "hot sauce",
                image: "hot-sauce-or-tabasco.png",
              },
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
          },
          {
            number: 4,
            step: "Pour the dressing over the salad.",
            ingredients: [],
            equipment: [],
          },
          {
            number: 5,
            step: "Fast, easy, and healthy-- one of my favorite lunches!",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/spicy-salad-with-kidney-beans-cheddar-and-nuts-157344",
  },
  {
    vegetarian: true,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 9,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 82.0,
    healthScore: 61.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 378.57,
    extendedIngredients: [
      {
        id: 11457,
        aisle: "Produce",
        image: "spinach.jpg",
        consistency: "solid",
        name: "baby spinach",
        nameClean: "baby spinach",
        original: "1 1/2 cup baby spinach",
        originalName: "baby spinach",
        amount: 1.5,
        unit: "cup",
        meta: [],
        measures: {
          us: { amount: 1.5, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 354.882, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: 10011080,
        aisle: "Produce",
        image: "beets-golden.jpg",
        consistency: "solid",
        name: "golden beets",
        nameClean: "golden beet",
        original:
          "1/3 cup roasted golden beets (see directions for roasting beets)",
        originalName:
          "roasted golden beets (see directions for roasting beets)",
        amount: 0.3333333333333333,
        unit: "cup",
        meta: ["for roasting beets)"],
        measures: {
          us: { amount: 0.333, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 78.863, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: 10011429,
        aisle: "Produce",
        image: "watermelon-radish.png",
        consistency: "solid",
        name: "watermelon radish",
        nameClean: "watermelon radish",
        original: "1 medium watermelon radish, thinly sliced",
        originalName: "watermelon radish, thinly sliced",
        amount: 1.0,
        unit: "medium",
        meta: ["thinly sliced"],
        measures: {
          us: { amount: 1.0, unitShort: "medium", unitLong: "medium" },
          metric: { amount: 1.0, unitShort: "medium", unitLong: "medium" },
        },
      },
      {
        id: 11429,
        aisle: "Produce",
        image: "radishes.jpg",
        consistency: "solid",
        name: "radishes",
        nameClean: "radish",
        original: "2 medium French breakfast radishes, thinly sliced",
        originalName: "French breakfast radishes, thinly sliced",
        amount: 2.0,
        unit: "medium",
        meta: ["french", "thinly sliced"],
        measures: {
          us: { amount: 2.0, unitShort: "medium", unitLong: "mediums" },
          metric: { amount: 2.0, unitShort: "medium", unitLong: "mediums" },
        },
      },
      {
        id: 9037,
        aisle: "Produce",
        image: "avocado.jpg",
        consistency: "solid",
        name: "avocado",
        nameClean: "avocado",
        original: "1/4 medium avocado, sliced",
        originalName: "avocado, sliced",
        amount: 0.25,
        unit: "medium",
        meta: ["sliced"],
        measures: {
          us: { amount: 0.25, unitShort: "medium", unitLong: "mediums" },
          metric: { amount: 0.25, unitShort: "medium", unitLong: "mediums" },
        },
      },
      {
        id: 1049003,
        aisle: "Produce",
        image: "apple.jpg",
        consistency: "solid",
        name: "fuji apple",
        nameClean: "fuji apple",
        original: "1/3 medium fuji apple, sliced",
        originalName: "fuji apple, sliced",
        amount: 0.3333333333333333,
        unit: "medium",
        meta: ["sliced"],
        measures: {
          us: { amount: 0.333, unitShort: "medium", unitLong: "mediums" },
          metric: { amount: 0.333, unitShort: "medium", unitLong: "mediums" },
        },
      },
      {
        id: 1019,
        aisle: "Cheese",
        image: "feta.png",
        consistency: "solid",
        name: "feta cheese",
        nameClean: "feta cheese",
        original: "1 Tbs feta cheese",
        originalName: "feta cheese",
        amount: 1.0,
        unit: "Tbs",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "Tbs", unitLong: "Tb" },
          metric: { amount: 1.0, unitShort: "Tbs", unitLong: "Tb" },
        },
      },
      {
        id: 12061,
        aisle: "Nuts",
        image: "almonds.jpg",
        consistency: "solid",
        name: "almonds",
        nameClean: "almonds",
        original: "1/2 Tbs sliced roasted almonds",
        originalName: "sliced roasted almonds",
        amount: 0.5,
        unit: "Tbs",
        meta: ["sliced"],
        measures: {
          us: { amount: 0.5, unitShort: "Tbs", unitLong: "Tbs" },
          metric: { amount: 0.5, unitShort: "Tbs", unitLong: "Tbs" },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "liquid",
        name: "olive oil",
        nameClean: "olive oil",
        original: "1 to 2 Tbs olive oil (for roasting beets)",
        originalName: "olive oil (for roasting beets)",
        amount: 1.0,
        unit: "Tbs",
        meta: ["(for roasting beets)"],
        measures: {
          us: { amount: 1.0, unitShort: "Tbs", unitLong: "Tb" },
          metric: { amount: 1.0, unitShort: "Tbs", unitLong: "Tb" },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "solid",
        name: "salt and pepper",
        nameClean: "salt and pepper",
        original: "salt and pepper to taste",
        originalName: "salt and pepper to taste",
        amount: 1.0,
        unit: "serving",
        meta: ["to taste"],
        measures: {
          us: { amount: 1.0, unitShort: "serving", unitLong: "serving" },
          metric: { amount: 1.0, unitShort: "serving", unitLong: "serving" },
        },
      },
    ],
    id: 661431,
    title: "Spring Salad with Radishes and Beets",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl:
      "https://www.foodista.com/recipe/RBW5C3NB/spring-salad-w-radishes-beets",
    image: "https://spoonacular.com/recipeImages/661431-556x370.jpg",
    imageType: "jpg",
    summary:
      'If you want to add more <b>gluten free, lacto ovo vegetarian, and primal</b> recipes to your recipe box, Spring Salad with Radishes and Beets might be a recipe you should try. This recipe serves 1. One serving contains <b>368 calories</b>, <b>8g of protein</b>, and <b>28g of fat</b>. For <b>$3.79 per serving</b>, this recipe <b>covers 27%</b> of your daily requirements of vitamins and minerals. It works well as a rather expensive side dish for <b>Spring</b>. Head to the store and pick up fuji apple, roasted golden beets, watermelon radish, and a few other things to make it today. 1 person found this recipe to be delicious and satisfying. From preparation to the plate, this recipe takes roughly <b>roughly 45 minutes</b>. It is brought to you by Foodista. Overall, this recipe earns a <b>super spoonacular score of 82%</b>. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/quinoa-salad-with-spring-radishes-and-greens-44389">Quinoa Salad With Spring Radishes And Greens</a>, <a href="https://spoonacular.com/recipes/spring-salad-with-radishes-and-pumpkin-seeds-14356">Spring Salad With Radishes And Pumpkin Seeds</a>, and <a href="https://spoonacular.com/recipes/spring-freekeh-salad-with-asparagus-peas-+-radishes-516264">spring freekeh salad with asparagus, peas + radishes</a>.',
    cuisines: [],
    dishTypes: ["side dish", "salad"],
    diets: ["gluten free", "lacto ovo vegetarian", "primal"],
    occasions: ["spring", "easter"],
    winePairing: {
      pairedWines: ["chardonnay", "gruener veltliner", "sauvignon blanc"],
      pairingText:
        "Chardonnay, Gruener Veltliner, and Sauvignon Blanc are my top picks for Salad. Sauvignon Blanc and Gruner Veltliner both have herby notes that complement salads with enough acid to match tart vinaigrettes, while a Chardonnay can be a good pick for creamy salad dressings.",
      productMatches: [
        {
          id: 442995,
          title: null,
          description:
            "Nestled in the heart of the Russian River Valley, Laguna Ranch Vineyard has been home to world-class Chardonnay for the past 30 years. The vineyard owes its long growing season to the cool fog that rolls in from the Pacific Ocean, giving our Chardonnay grapes a delicate balance between crisp acidity and ripe fruit flavors. An elegant expression of its namesake vineyard, Laguna Ranch Vineyard Chardonnay is an exceptionally well-balanced and luxurious wine. Opens with notes of apple, pear, quince and tangerine, framed by sweet undertones of Asian spice. Well balanced and rich, this Chardonnay has an expressive mouthfeel and a layered, lingering finish.",
          price: "$15.99",
          imageUrl: "https://spoonacular.com/productImages/442995-312x231.jpg",
          averageRating: 0.82,
          ratingCount: 8.0,
          score: 0.7799999999999999,
          link: "https://click.linksynergy.com/deeplink?id=*QCiIS6t4gA&mid=2025&murl=https%3A%2F%2Fwww.wine.com%2Fproduct%2Flaguna-winery-russian-river-chardonnay-2008%2F107334",
        },
      ],
    },
    instructions:
      "Preheat the oven to 375F. Line a baking sheet with parchment paper or a silicone mat.\nPeel 3-4 medium beets and dice them into small cubes.\nIn a medium-sized bowl, toss the beets with 1 to 2 tablespoons of olive oil. Sprinkle a dash of salt on the beets and mix again. Spread the beets onto a baking sheet in a single layer.\nBake for about 30 to 35 minutes, or until they can be easily pierced with a fork.\nIn a small bowl, mix the spinach, radishes, 1/3 cup beets, feta, and sliced almonds together.\nPour the salad onto a plate and top with sliced avocado and apples.\nRefrigerate any leftover beets in an airtight container\nSeason salad with salt and pepper and enjoy with your dressing of choice.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat the oven to 375F. Line a baking sheet with parchment paper or a silicone mat.",
            ingredients: [],
            equipment: [
              {
                id: 404770,
                name: "baking paper",
                localizedName: "baking paper",
                image: "baking-paper.jpg",
              },
              {
                id: 404727,
                name: "baking sheet",
                localizedName: "baking sheet",
                image: "baking-sheet.jpg",
              },
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
                temperature: { number: 375.0, unit: "Fahrenheit" },
              },
            ],
          },
          {
            number: 2,
            step: "Peel 3-4 medium beets and dice them into small cubes.",
            ingredients: [
              {
                id: 11080,
                name: "beet",
                localizedName: "beet",
                image: "beets.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "In a medium-sized bowl, toss the beets with 1 to 2 tablespoons of olive oil.",
            ingredients: [
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 11080,
                name: "beet",
                localizedName: "beet",
                image: "beets.jpg",
              },
            ],
            equipment: [
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
          },
          {
            number: 4,
            step: "Sprinkle a dash of salt on the beets and mix again.",
            ingredients: [
              {
                id: 11080,
                name: "beet",
                localizedName: "beet",
                image: "beets.jpg",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: "Spread the beets onto a baking sheet in a single layer.",
            ingredients: [
              { id: 0, name: "spread", localizedName: "spread", image: "" },
              {
                id: 11080,
                name: "beet",
                localizedName: "beet",
                image: "beets.jpg",
              },
            ],
            equipment: [
              {
                id: 404727,
                name: "baking sheet",
                localizedName: "baking sheet",
                image: "baking-sheet.jpg",
              },
            ],
          },
          {
            number: 6,
            step: "Bake for about 30 to 35 minutes, or until they can be easily pierced with a fork.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: { number: 30, unit: "minutes" },
          },
          {
            number: 7,
            step: "In a small bowl, mix the spinach, radishes, 1/3 cup beets, feta, and sliced almonds together.",
            ingredients: [
              {
                id: 10112061,
                name: "sliced almonds",
                localizedName: "sliced almonds",
                image: "almonds.jpg",
              },
              {
                id: 11429,
                name: "radish",
                localizedName: "radish",
                image: "radishes.jpg",
              },
              {
                id: 10011457,
                name: "spinach",
                localizedName: "spinach",
                image: "spinach.jpg",
              },
              {
                id: 11080,
                name: "beet",
                localizedName: "beet",
                image: "beets.jpg",
              },
              {
                id: 1019,
                name: "feta cheese",
                localizedName: "feta cheese",
                image: "feta.png",
              },
            ],
            equipment: [
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
          },
          {
            number: 8,
            step: "Pour the salad onto a plate and top with sliced avocado and apples.",
            ingredients: [
              {
                id: 9037,
                name: "avocado",
                localizedName: "avocado",
                image: "avocado.jpg",
              },
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 9,
            step: "Refrigerate any leftover beets in an airtight container",
            ingredients: [
              {
                id: 11080,
                name: "beet",
                localizedName: "beet",
                image: "beets.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 10,
            step: "Season salad with salt and pepper and enjoy with your dressing of choice.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/spring-salad-with-radishes-and-beets-661431",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 19,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 92.0,
    healthScore: 100.0,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 430.62,
    extendedIngredients: [
      {
        id: 11011,
        aisle: "Produce",
        image: "asparagus.png",
        consistency: "solid",
        name: "asparagus",
        nameClean: "asparagus",
        original: "1 cup asparagus cut into few inch pieces",
        originalName: "asparagus cut into few inch pieces",
        amount: 1.0,
        unit: "cup",
        meta: ["cut into few inch pieces"],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 236.588, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: 9037,
        aisle: "Produce",
        image: "avocado.jpg",
        consistency: "solid",
        name: "avocado",
        nameClean: "avocado",
        original: "1 avocado",
        originalName: "avocado",
        amount: 1.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "", unitLong: "" },
          metric: { amount: 1.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "solid",
        name: "garlic clove",
        nameClean: "garlic",
        original: "1 garlic clove minced",
        originalName: "garlic clove minced",
        amount: 1.0,
        unit: "",
        meta: ["minced"],
        measures: {
          us: { amount: 1.0, unitShort: "", unitLong: "" },
          metric: { amount: 1.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 19296,
        aisle: "Nut butters, Jams, and Honey",
        image: "honey.png",
        consistency: "liquid",
        name: "honey",
        nameClean: "honey",
        original: "1/2 teaspoon honey or agave",
        originalName: "honey or agave",
        amount: 0.5,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
          metric: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
        },
      },
      {
        id: 9152,
        aisle: "Produce",
        image: "lemon-juice.jpg",
        consistency: "liquid",
        name: "juice of lemon",
        nameClean: "lemon juice",
        original: "1/2 Juice of lemon",
        originalName: "Juice of lemon",
        amount: 0.5,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 0.5, unitShort: "", unitLong: "" },
          metric: { amount: 0.5, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "liquid",
        name: "olive oil",
        nameClean: "olive oil",
        original: "2 tablespoons olive oil",
        originalName: "olive oil",
        amount: 2.0,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
        },
      },
      {
        id: 20035,
        aisle: "Pasta and Rice;Health Foods",
        image: "uncooked-quinoa.png",
        consistency: "solid",
        name: "quinoa",
        nameClean: "quinoa",
        original: "1 cup quinoa",
        originalName: "quinoa",
        amount: 1.0,
        unit: "cup",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "cup", unitLong: "cup" },
          metric: { amount: 236.588, unitShort: "ml", unitLong: "milliliters" },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "solid",
        name: "salt",
        nameClean: "table salt",
        original: "1/2 teaspoon salt",
        originalName: "salt",
        amount: 0.5,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
          metric: { amount: 0.5, unitShort: "tsps", unitLong: "teaspoons" },
        },
      },
      {
        id: 1042027,
        aisle: null,
        image: "seasoning.png",
        consistency: "solid",
        name: "seasoning",
        nameClean: "seasoning",
        original: "1 teaspoon Italian herb seasoning",
        originalName: "Italian herb seasoning",
        amount: 1.0,
        unit: "teaspoon",
        meta: ["italian"],
        measures: {
          us: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
          metric: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
        },
      },
      {
        id: 11677,
        aisle: "Produce",
        image: "shallots.jpg",
        consistency: "solid",
        name: "shallots",
        nameClean: "shallot",
        original: "2 shallots",
        originalName: "shallots",
        amount: 2.0,
        unit: "",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "", unitLong: "" },
          metric: { amount: 2.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 11955,
        aisle: "Canned and Jarred;Produce",
        image: "sundried-tomatoes.jpg",
        consistency: "solid",
        name: "sun-dried tomatoes",
        nameClean: "sun dried tomatoes",
        original: "1/2 cup sun dried tomatoes",
        originalName: "sun dried tomatoes",
        amount: 0.5,
        unit: "cup",
        meta: ["dried"],
        measures: {
          us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 118.294, unitShort: "ml", unitLong: "milliliters" },
        },
      },
    ],
    id: 657679,
    title: "Quinoa Salad With Avocado, Asparagus and Sun Dried Tomatoes",
    readyInMinutes: 45,
    servings: 2,
    sourceUrl:
      "http://www.foodista.com/recipe/NRZZ4FGK/quinoa-salad-with-avocado-asparagus-and-sun-dried-tomatoes",
    image: "https://spoonacular.com/recipeImages/657679-556x370.jpg",
    imageType: "jpg",
    summary:
      'Quinoa Salad With Avocado, Asparagus and Sun Dried Tomatoes might be just the main course you are searching for. For <b>$4.31 per serving</b>, this recipe <b>covers 41%</b> of your daily requirements of vitamins and minerals. This recipe makes 2 servings with <b>715 calories</b>, <b>20g of protein</b>, and <b>35g of fat</b> each. Only a few people made this recipe, and 1 would say it hit the spot. A mixture of salt, olive oil, sun tomatoes, and a handful of other ingredients are all it takes to make this recipe so delicious. To use up the juice of lemon you could follow this main course with the <a href="https://spoonacular.com/recipes/fruit-juice-pops-433326">Fruit Juice Pops</a> as a dessert. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. It is a good option if you\'re following a <b>gluten free and dairy free</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 92%</b>. This score is super. Similar recipes include <a href="https://spoonacular.com/recipes/spinach-quiche-with-sun-dried-tomatoes-923350">Spinach Quiche with Sun-Dried Tomatoes</a>, <a href="https://spoonacular.com/recipes/lemon-quinoa-salad-with-pistachios-sun-dried-tomatoes-584449">Lemon Quinoa Salad with Pistachios & Sun-Dried Tomatoes</a>, and <a href="https://spoonacular.com/recipes/pasta-salad-with-asparagus-corn-and-sun-dried-tomatoes-749165">Pasta Salad With Asparagus, Corn and Sun-Dried Tomatoes</a>.',
    cuisines: [],
    dishTypes: ["salad"],
    diets: ["gluten free", "dairy free"],
    occasions: [],
    winePairing: {},
    instructions:
      "<ol><li>Rinse quinoa under cold running water for a minute or two to get rid of the bitter aftertaste.</li><li>Transfer to a pot or rice cooker, add 2 cups of water, salt, cover and bring to a boil. Lower down the heat and cook 15 min or until water is absorbed.</li><li>In another pot bring water to a boil, add asparagus and simmer 5-8 min or until soft.</li><li>When ready cool down the quinoa and asparagus. Meanwhile chop all the veggie ingredients.</li><li>Prepare the dressing by simply mixing all of its ingredients (lemon juice, 2 tbs olive oil, 1 garlic clove, 1 tsp italian seasoning, 1/2 tsp honey, pinch of salt) in a bowl.</li><li>In a bowl combine quinoa, avocado, asparagus, sun dried tomatoes and shallots. Pour the dressing and mix until all is combined.</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Rinse quinoa under cold running water for a minute or two to get rid of the bitter aftertaste.",
            ingredients: [
              {
                id: 20035,
                name: "quinoa",
                localizedName: "quinoa",
                image: "uncooked-quinoa.png",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
            ],
            equipment: [],
          },
          {
            number: 2,
            step: "Transfer to a pot or rice cooker, add 2 cups of water, salt, cover and bring to a boil. Lower down the heat and cook 15 min or until water is absorbed.In another pot bring water to a boil, add asparagus and simmer 5-8 min or until soft.When ready cool down the quinoa and asparagus. Meanwhile chop all the veggie ingredients.Prepare the dressing by simply mixing all of its ingredients (lemon juice, 2 tbs olive oil, 1 garlic clove, 1 tsp italian seasoning, 1/2 tsp honey, pinch of salt) in a bowl.In a bowl combine quinoa, avocado, asparagus, sun dried tomatoes and shallots.",
            ingredients: [
              {
                id: 11955,
                name: "sun dried tomatoes",
                localizedName: "sun dried tomatoes",
                image: "sundried-tomatoes.jpg",
              },
              {
                id: 1022027,
                name: "italian seasoning",
                localizedName: "italian seasoning",
                image: "dried-herbs.png",
              },
              {
                id: 10211215,
                name: "whole garlic cloves",
                localizedName: "whole garlic cloves",
                image: "garlic.jpg",
              },
              {
                id: 9152,
                name: "lemon juice",
                localizedName: "lemon juice",
                image: "lemon-juice.jpg",
              },
              {
                id: 11011,
                name: "asparagus",
                localizedName: "asparagus",
                image: "asparagus.png",
              },
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 11677,
                name: "shallot",
                localizedName: "shallot",
                image: "shallots.jpg",
              },
              {
                id: 9037,
                name: "avocado",
                localizedName: "avocado",
                image: "avocado.jpg",
              },
              {
                id: 20035,
                name: "quinoa",
                localizedName: "quinoa",
                image: "uncooked-quinoa.png",
              },
              {
                id: 19296,
                name: "honey",
                localizedName: "honey",
                image: "honey.png",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [
              {
                id: 404662,
                name: "rice cooker",
                localizedName: "rice cooker",
                image: "rice-cooker.jpg",
              },
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
            length: { number: 23, unit: "minutes" },
          },
          {
            number: 3,
            step: "Pour the dressing and mix until all is combined.",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/quinoa-salad-with-avocado-asparagus-and-sun-dried-tomatoes-657679",
  },
];
